const swaggerUi = require('swagger-ui-express');
const swaggerJsDoc = require('swagger-jsdoc');
const options = {
    swaggerDefinition: {
        info: {
            title: 'Test API',
            version: '1.0.0',
            description: 'Text express API with autogenerated swagger doc',
        },
        basePath: '/',
    },
    swagger: "2.0",
    apis: ['./endpoints.js']
};

const swaggerSpec = swaggerJsDoc(options)
module.exports = (app) => {
    app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec))
}